# Generated by Django 3.1.13 on 2021-11-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonentity',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='pokemonentity',
            name='lon',
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='Lat'),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='lontitude',
            field=models.FloatField(null=True, verbose_name='Lon'),
        ),
    ]
